"""Add new tables

Revision ID: 167efe3dfe2f
Revises: 6e4684934bec
Create Date: 2025-10-10 17:12:48.504983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167efe3dfe2f'
down_revision: Union[str, None] = '6e4684934bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_abrir_puertas', sa.String(), nullable=True),
    sa.Column('horario_cerrar_puertas', sa.String(), nullable=True),
    sa.Column('abierto', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parque_id'), 'parque', ['id'], unique=False)
    op.create_table('estado_horario',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('requiere_talle', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividad_id'), 'actividad', ['id'], unique=False)
    op.create_table('visitante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('dni', sa.Integer(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('talle', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitante_id'), 'visitante', ['id'], unique=False)
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_actividad', sa.Integer(), nullable=True),
    sa.Column('hora_inicio', sa.String(), nullable=True),
    sa.Column('hora_fin', sa.String(), nullable=True),
    sa.Column('cupo_total', sa.Integer(), nullable=True),
    sa.Column('cupo_ocupado', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['estado'], ['estado_horario.nombre'], ),
    sa.ForeignKeyConstraint(['id_actividad'], ['actividad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horario_id'), 'horario', ['id'], unique=False)
    op.create_table('inscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_horario', sa.Integer(), nullable=True),
    sa.Column('id_visitante', sa.Integer(), nullable=True),
    sa.Column('nro_personas', sa.Integer(), nullable=True),
    sa.Column('acepta_Terminos_Condiciones', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_horario'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['id_visitante'], ['visitante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscripcion_id'), 'inscripcion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inscripcion_id'), table_name='inscripcion')
    op.drop_table('inscripcion')
    op.drop_index(op.f('ix_horario_id'), table_name='horario')
    op.drop_table('horario')
    op.drop_index(op.f('ix_visitante_id'), table_name='visitante')
    op.drop_table('visitante')
    op.drop_index(op.f('ix_actividad_id'), table_name='actividad')
    op.drop_table('actividad')
    op.drop_table('estado_horario')
    op.drop_index(op.f('ix_parque_id'), table_name='parque')
    op.drop_table('parque')
    # ### end Alembic commands ###
